version: "3"
services:
  web1:
    build: ./docker/web1
    container_name: web1-container
    ports:
      - 8080:80
    volumes:
      - ./web1/public:/usr/local/apache2/htdocs
  web2:
    build: ./docker/web2
    container_name: web2-container
    ports:
      - 9090:80
    volumes:
      - ./web2/public:/usr/local/apache2/htdocs